layout_spectrum: 0.8297873
name: teeism
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.7364776
  lightness: 0.6404255
  saturation: 0.1808511
  rhythmicContrast: 0.1212766
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.4468085
