name: teeism
favicon: null
layout_spectrum: 0.8297873
typography_spectrum: 0.4468085
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaebed'
    - '#8b8b8d'
    - '#5d5d5f'
    - '#aaaaac'
    - '#000000'
  brandStrength: 0.5625
  lightness: 0.8125
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
