layout_spectrum: 0.8297873
typography_spectrum: 0.2964195
color:
  lightness: 0.4771144
  brandStrength: 0.7364776
  saturation: 0.4318199
  rhythmicContrast: 0.110447
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: teeism
